"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
archive = "mise run clean-sims"

[scripts.run.run]
available_in = ["local"]
command = "mise run run"
default = true
icon = "play"

[scripts.run.xcode]
available_in = ["local"]
command = "mise -C ios run xcode"
icon = "hammer"
