"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
archive = "mise run clean-sims"
run_mode = "nonconcurrent"

[scripts.run.run]
available_in = ["local"]
command = "mise run run"
default = true
icon = "play"

[scripts.run.physical]
available_in = ["local"]
command = "mise -C ios run deploy -- id=00008140-000611C801F3001C --attach"
icon = "smartphone"

[scripts.run.xcode]
available_in = ["local"]
command = "mise -C ios run xcode"
icon = "hammer"

[scripts.run.tauri]
available_in = ["local"]
command = "mise run tauri"
icon = "monitor"

[scripts.run.server]
available_in = ["local"]
command = "mise run server dev"
icon = "server"
