import Foundation

extension Workspace {
    private static let defaultPreviewDate = Date(timeIntervalSince1970: 1_783_555_200)

    public static func preview(
        id: String = "workspace-1",
        activeSessionID: String? = nil,
        archiveCommit: String? = nil,
        assigneeUserID: String? = nil,
        bigTerminalMode: Int? = nil,
        branch: String? = nil,
        createdAt: Date? = nil,
        creatorClientID: String? = nil,
        creatorUserID: String? = nil,
        derivedStatus: String? = nil,
        directoryName: String? = nil,
        hostingServerURL: String? = nil,
        initializationFilesCopied: Int? = nil,
        initializationLogPath: String? = nil,
        initializationParentBranch: String? = nil,
        intendedTargetBranch: String? = nil,
        linkedDirectoryPaths: String? = nil,
        linkedWorkspaceIDs: String? = nil,
        manualStatus: String? = nil,
        notes: String? = nil,
        organizationID: String? = nil,
        permissionLevel: String? = nil,
        pinnedAt: String? = nil,
        placeholderBranchName: String? = nil,
        prDescription: String? = nil,
        prTitle: String? = nil,
        remoteFileSyncEnabled: Int? = nil,
        repositoryID: String? = nil,
        sandboxProvider: String? = nil,
        secondaryDirectoryName: String? = nil,
        setupLogPath: String? = nil,
        state: State? = .ready,
        unread: Int? = nil,
        updatedAt: Date? = nil,
        userSetBranchName: Int? = nil,
        userSetWorkspaceName: Int? = nil,
        watcherUserIDs: String? = nil,
        workspaceName: String? = nil,
        workspacePath: String? = nil,
        isWorking: Bool = false
    ) -> Self {
        Self(
            id: id,
            activeSessionID: activeSessionID,
            archiveCommit: archiveCommit,
            assigneeUserID: assigneeUserID,
            bigTerminalMode: bigTerminalMode,
            branch: branch,
            createdAt: createdAt ?? defaultPreviewDate,
            creatorClientID: creatorClientID,
            creatorUserID: creatorUserID,
            derivedStatus: derivedStatus,
            directoryName: directoryName,
            hostingServerURL: hostingServerURL,
            initializationFilesCopied: initializationFilesCopied,
            initializationLogPath: initializationLogPath,
            initializationParentBranch: initializationParentBranch,
            intendedTargetBranch: intendedTargetBranch,
            linkedDirectoryPaths: linkedDirectoryPaths,
            linkedWorkspaceIDs: linkedWorkspaceIDs,
            manualStatus: manualStatus,
            notes: notes,
            organizationID: organizationID,
            permissionLevel: permissionLevel,
            pinnedAt: pinnedAt,
            placeholderBranchName: placeholderBranchName,
            prDescription: prDescription,
            prTitle: prTitle,
            remoteFileSyncEnabled: remoteFileSyncEnabled,
            repositoryID: repositoryID,
            sandboxProvider: sandboxProvider,
            secondaryDirectoryName: secondaryDirectoryName,
            setupLogPath: setupLogPath,
            state: state,
            unread: unread,
            updatedAt: updatedAt ?? defaultPreviewDate,
            userSetBranchName: userSetBranchName,
            userSetWorkspaceName: userSetWorkspaceName,
            watcherUserIDs: watcherUserIDs,
            workspaceName: workspaceName,
            workspacePath: workspacePath,
            isWorking: isWorking
        )
    }
}
